apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: hazelcast
  name: hazelcast
spec:
  type: NodePort
  ports:
    - port: 5701
  selector: 
    name: hazelcast
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hazelcast
  labels:
    name: hazelcast
spec: 
  replicas: 1
  template: 
    metadata: 
        labels: 
            name: hazelcast
    spec: 
        containers: 
        - name: hazelcast
          #image: quay.io/pires/hazelcast-kubernetes:3.9.3
          image: mycat/hazelcast-kubernetes
          name: hazelcast
          imagePullPolicy: IfNotPresent
          env:
            - name: "DNS_DOMAIN"
              value: "cluster.local"
            - name: "HC_GROUP_NAME"
              value: "someGroup"                
            - name: "HC_GROUP_PASSWORD"
              value: "123456"          
            - name: POD_NAMESPACE
              valueFrom:
                 fieldRef:
                    fieldPath: metadata.namespace
          ports: 
            - containerPort: 5701
              name: hazelcast
                
